version: '2'
services:
  cloud-config-server:
    image: hyness/spring-cloud-config-server:latest
    expose:
      - '${http_port}'
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: '${config_git_repo_uri}'
      SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME: '${git_repo_username}'
      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: '${git_repo_password}'